{% set version = "0.5.7" %}

package:
  name: colorful
  version: {{ version }}

source:
  url: https://github.com/timofurrer/colorful/archive/v{{ version }}.zip
  sha256: 3fde99f3cf49963d556b6dd45b322cefffbe447988c50a485bb697bcab4396e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

# Need these up here for conda-smithy to handle them properly.
requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - colorama

test:
  imports:
    - colorful

about:
  home: http://github.com/timofurrer/colorful
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Terminal string styling done right, in Python'
  description: |
    Terminal string styling done right, in Python.
    Key Features:
      * expressive and consistent API
      * support for different color modes (8 ANSI, 256 ANSI, true colors)
      * support for predefined awesome styles (solarized, ...)
      * support for custom color palettes
      * support nesting styles
      * support for different platforms (using colorama on Windows)
      * context managers for clean color mode, color palette or style switch
      * support len() on colored strings
      * support color names from X11 rgb.txt
      * no dependencies

  doc_url: https://github.com/timofurrer/colorful
  dev_url: https://github.com/timofurrer/colorful

extra:
  recipe-maintainers:
    - vnlitvinov
    - timofurrer
